# Generated by Django 6.0.3 on 2026-03-19 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_id', models.CharField(editable=False, help_text='ID pseudonimizzato (es. PAZ-20260319-A7F2)', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Note cliniche generali (NO nome/cognome/CF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data della sessione')),
                ('pain_level', models.IntegerField(blank=True, help_text='Livello dolore VAS 0-10', null=True)),
                ('medications', models.TextField(blank=True, help_text='Farmaci assunti')),
                ('footwear', models.CharField(blank=True, help_text='Tipo di calzatura', max_length=100)),
                ('assistive_device', models.CharField(blank=True, help_text='Ausilio deambulazione (nessuno, stampella, deambulatore...)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Note sulla sessione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_operated', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('10MWT', '10-Meter Walk Test'), ('TREADMILL_SSWS', 'Treadmill SSWS'), ('TUG', 'Timed Up and Go'), ('ROMBERG', 'Test di Romberg'), ('6MWT', '6-Minute Walk Test'), ('BBS', 'Berg Balance Scale'), ('OTHER', 'Altro')], max_length=20)),
                ('trial_number', models.IntegerField(default=1, help_text='Numero del trial (1, 2, 3...)')),
                ('value', models.FloatField(blank=True, help_text='Valore numerico principale (es. velocità m/s, tempo s)', null=True)),
                ('unit', models.CharField(default='m/s', help_text='Unità di misura', max_length=20)),
                ('extra_data', models.JSONField(blank=True, help_text='Dati aggiuntivi in formato JSON', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='patients.session')),
            ],
            options={
                'ordering': ['test_type', 'trial_number'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('recipient_type', models.CharField(choices=[('PATIENT', 'Paziente'), ('DOCTOR', 'Medico prescrittore')], max_length=10)),
                ('recipient_name', models.CharField(blank=True, help_text="Nome del destinatario (es. 'Dr. Rossi')", max_length=200)),
                ('expires_at', models.DateTimeField(help_text='Data/ora di scadenza del link')),
                ('max_access_count', models.IntegerField(default=50, help_text='Numero massimo di accessi consentiti')),
                ('access_count', models.IntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='patients.patient')),
                ('session', models.ForeignKey(blank=True, help_text='Se vuoto, condivide tutte le sessioni del paziente', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True, help_text='False se password errata o link scaduto')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='patients.sharelink')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Descrizione breve (es. 'Treadmill trial 1')", max_length=200)),
                ('file', models.FileField(upload_to='videos/%Y/%m/')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Durata in secondi', null=True)),
                ('face_blurred', models.BooleanField(default=False, help_text='Il volto è stato blurrato?')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='patients.session')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
