server {
    listen 80;
    server_name 3d-ga.it www.3d-ga.it;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://3d-ga.it$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 3d-ga.it www.3d-ga.it;

    ssl_certificate /etc/letsencrypt/live/3d-ga.it/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3d-ga.it/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        autoindex off;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        client_max_body_size 500M;
        proxy_read_timeout 120s;
    }
}
