# Generated by Django 6.0.3 on 2026-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo_id', models.CharField(db_index=True, help_text='ID pseudonimizzato (deve corrispondere a Patient.pseudo_id)', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fiscal_code', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('referring_doctor', models.CharField(blank=True, max_length=200, verbose_name='Medico prescrittore')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identità Paziente',
                'verbose_name_plural': 'Identità Pazienti',
                'db_table': 'patient_identity',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
